services:
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  application:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres: